export default function Home(){
    return(
        <div className="home">
            <img src="https://bannerughattabiopark.org/assets/images/slider/slider9.jpg" id="home-img" alt="slider"></img>
        <h2>OUR ESTEEMED ADOPTERS / DONORS (LIST)</h2>
        <p>Bannerughatta Biological Park Bengaluru (BBBP) was carved out of Bannerghatta National Park (BNP) vide notification No FEE 19 FWL 98, Bangalore, Dated: 5th March 2004 and was brought under the administrative judistruction of the Zoo Authority of Karnataka
(ZAK), Government of Karnataka (GOK)</p>
<p>The Bannerghatta Park has various units such as Zoo, Safari and Butterfly park spread over 731.88 Ha. The field activities of the biological park are many fold as it is classified as one of the major zoo in the state/country with a lot of scope for scientific development. The activities prevailing in the Biological Park are Maintenance of zoo - which exhibits varieties of birds, reptiles and mammals within the well maintained enclosures. Running and maintenance of safaris - drive of the tourists through the animals' enclosures in the vehicles i.e. tigers, lions, bears and herbivores safaris and also for breeding of endangered species of animals /ungulates; Rescue Centers to provide life time facilities to the rescued animals like tigers, lions and bears from circuses, madharies etc., Butterfly park; Nature camp for the people those wish to stay and study the flora and fauna in forests; tourism and facilities to visitors; feeding and health care to captive animals; with inbuilt administrative set up to manage all the affairs of the Bannerghatta Biological Park</p>
        <img src="https://bannerughattabiopark.org/assets/images/t6.png" id="img" alt="img"></img>
        <img src="https://bannerughattabiopark.org/assets/images/t2.png" id="seimg" alt="seimg"></img>
        <img src="https://bannerughattabiopark.org/assets/images/t4.png" id="thimg" alt="thimg"></img>
        <img src="https://bannerughattabiopark.org/assets/images/t1.png" id="foimg" alt="fiimg"></img>
        <img src="https://bannerughattabiopark.org/assets/images/t3.png"  id="fiimg" alt="fiimg"></img>
        <img src="https://bannerughattabiopark.org/assets/images/t5.png" id="siimg" alt="siimg"></img>
        <h2>PREPARENDNSS</h2>
        <li>Wear clothing that merge with nature. Avoid wearing florescent/bright colour clothing</li>
        <li>Wear comfortable shoes, carry a backpack, water bottle, hat, headphone (BBP is a silent zone), raincoat, etc. You may have to walk about 2 to 3 km.</li>
        <li>Safari tickets are limited in number.</li>
        <li>Facilities:- Cloak room, wheelchairs, Toilets, resting places, hand sanitizers, paper bags, information etc</li>
        <li>Book tickets online.</li>
        <li>Single use plastic covers/ items are not permitted inside the zoo. Such items are replaced with paper bag at the entrance checking gate</li>
        <li>Please note that BBP is a safe place to visit.</li>
        <li>Any liquids and essential food items should be securely contained in a multiuse container in the backpack in order to avoid snatching by free ranging monkeys.</li>
        <li>We encourage you to carry back waste generated by you and dispose it within BBMP limits.</li>
        <li>Wish everyone an enriching, educative experience in the Park!</li>
        </div>
       
    );

     
}